name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - 'app/client/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: cd app/client && docker build -t webmakaka/microservices-client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push webmakaka/microservices-client
      # - uses: digitalocean/actions-doctl@v2
      #   with:
      #     token: ${{secretes.DIGITAL_OCEAN_ACCESS_TOKEN}}
      # - run: doctl kubernetes cluster kubeconfig save <kubernetes_cluster_name>
      # - run: kubectl rollout restart deployment client-depl
